permission: 'em.admin'
lobby:
  location:
    ==: org.bukkit.Location
    x: 0
    y: 70
    z: 0
    yaw: -157.1997
    pitch: 1.9499522
    world: world
leaveItem:
  material: BARRIER
  name: '&cLeave from arena &7(Right click)'
game:
  max_players: 4
  min_players: 2
  seconds_start: 10
  costOfWin: 100.0
  neededBlockToWin: 100