name: ExampleMiniGame
main: pl.timsixth.exampleminigame.ExampleMiniGamePlugin
version: '1.0.0'
api-version: 1.13
author: timsixth
depend:
  - T-MiniGameAPI
softdepend:
  - Multiverse-Core
  - T-DatabasesApi
commands:
  em:
  aem: